# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170829_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('type', models.CharField(choices=[(1, '\u6ce8\u518c'), (2, '\u627e\u56de\u5bc6\u7801')], max_length=1, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b')),
                ('send_time', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u9001\u65f6\u95f4')),
            ],
            options={
                'db_table': 't_email_verify',
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='brief',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(b'1', '\u7537'), (b'2', '\u5973')], default=b'0', max_length=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(b'1', '\u5b66\u751f'), (b'2', '\u8001\u5e08')], default=b'0', max_length=1, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
    ]
