# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('brief', models.CharField(max_length=256, verbose_name='\u7b80\u4ecb')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 't_author',
                'verbose_name': '\u4f5c\u8005\u8868',
                'verbose_name_plural': '\u4f5c\u8005\u8868',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('brief', models.CharField(max_length=256, verbose_name='\u7b80\u4ecb')),
                ('author', models.ManyToManyField(to='books.Author')),
            ],
            options={
                'db_table': 't_book',
                'verbose_name': '\u56fe\u4e66\u8868',
                'verbose_name_plural': '\u56fe\u4e66\u8868',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_cid', models.IntegerField(default=0, verbose_name='\u4e0a\u4e00\u7ae0id')),
                ('next_cid', models.IntegerField(default=0, verbose_name='\u4e0b\u4e00\u7ae0id')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
            options={
                'db_table': 't_content',
                'verbose_name': '\u76ee\u5f55\u8868',
                'verbose_name_plural': '\u76ee\u5f55\u8868',
            },
        ),
    ]
