# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': '\u6392\u884c', 'verbose_name_plural': '\u6392\u884c'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '\u9891\u9053', 'verbose_name_plural': '\u9891\u9053'},
        ),
        migrations.AlterField(
            model_name='ranking',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u540d\u79f0'),
        ),
    ]
