# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True, verbose_name='\u5173\u952e\u5b57')),
                ('is_hot', models.BooleanField(default=False, verbose_name='\u70ed\u8bcd')),
                ('count', models.IntegerField(default=1, verbose_name='\u6b21\u6570')),
            ],
            options={
                'db_table': 't_hot_word',
                'verbose_name': '\u5173\u952e\u5b57',
                'verbose_name_plural': '\u5173\u952e\u5b57',
            },
        ),
    ]
