# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_auto_20170907_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('desc', models.CharField(max_length=256, verbose_name='\u63cf\u8ff0')),
                ('order', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('status', models.IntegerField(choices=[(0, '\u5ba1\u6838'), (1, '\u4e0a\u67b6'), (2, '\u4e0b\u67b6')], default=0, verbose_name='\u72b6\u6001')),
                ('icon', models.ImageField(blank=True, null=True, storage=utils.storage.ImageStorage(), upload_to='icons/')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Classification', verbose_name='\u5206\u7c7b')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Column', verbose_name='\u680f\u76ee')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Ranking', verbose_name='\u6392\u884c')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Topic', verbose_name='\u4e13\u9898')),
            ],
            options={
                'ordering': ('order',),
                'db_table': 't_menu',
                'verbose_name': '\u83dc\u5355',
                'verbose_name_plural': '\u83dc\u5355',
            },
        ),
    ]
