# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='\u5173\u952e\u5b57')),
            ],
            options={
                'db_table': 't_hot_word',
                'verbose_name': '\u5173\u952e\u5b57\u8868',
                'verbose_name_plural': '\u5173\u952e\u5b57\u8868',
            },
        ),
        migrations.CreateModel(
            name='HotWordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='\u552f\u4e00\u7801')),
            ],
            options={
                'db_table': 't_hot_word_type',
                'verbose_name': '\u5173\u952e\u5b57\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u5173\u952e\u5b57\u7c7b\u578b\u8868',
            },
        ),
        migrations.AddField(
            model_name='hotword',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotword.HotWordType', verbose_name='\u7c7b\u578b'),
        ),
    ]
