# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('desc', models.CharField(max_length=256, verbose_name='\u63cf\u8ff0')),
                ('img', models.ImageField(storage=utils.storage.ImageStorage(), upload_to=b'images/', verbose_name='\u56fe\u7247')),
                ('type', models.IntegerField(default=0, verbose_name='\u7c7b\u578b')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.Book')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='subject.Topic')),
            ],
            options={
                'db_table': 't_banner',
                'verbose_name': '\u5e7f\u544a\u8868',
                'verbose_name_plural': '\u5e7f\u544a\u8868',
            },
        ),
    ]
